### PR TITLE
Recreate apidb schema

### PR DESCRIPTION
**Pull request by wbazant**
Done when installing the schema on mbio-rbld.

To test I did this:
installApidbSchema --db mbio-rbld --dropApiDB --allowFailures ; installApidbSchema --db mbio-rbld --dropGUS --allowFailures ; build GUS install -append -installDBSchemaSkipRoles ; installApidbSchema --db mbio-rbld --create

until there were no more errors.

### CODE REVIEW

**Comment by wbazant** [comment]
I've encountered this when trying to build a schema, and then @iodice said that this is what @jaycolin saw.

I've then gone and read what you said @kathryncrouch, would you know what to do with this PR? It solves my immediate problem of being able to create the schema, but I don't know what it will do to the dump.

**Comment by kathryncrouch** [comment]
I don't know what this will do to the dump either. I am not sure how this works at the moment - it seems counterintuitive that importing the chebi dump happens in the workflow if you can't run installApidbSchema without the tables. We must have done this before, maybe @jbrestel remembers how we got around this last time?

**Comment by jbrestel** [comment]
chebi is a bit of an exception for us.  I think adding the fk constraint is a work Ross/Kathryn have done recently

we load all of chebi from an oracle dump.  the tables can not be defined when the dumper runs. 
ftp://ftp.ebi.ac.uk/pub/databases/chebi/Oracle_dumps/

I think what we need to do is add the constraint after the oracle dump finishes not during the initial schema install

**Comment by kathryncrouch** [comment]
No, I didn't do this.  Git blame says it was you @jbrestel :)  Although the svn -> git migration did mess some of that stuff up.  Whoever did it, I suspect it was done to fix constraints on tables in an existing db and we didn't think about creating a new schema at the time.  Anyway, the createChebiSchema.sql elsewhere and running it as a workflow step immediately after the dump seems like the best solution to me too.

**Comment by jbrestel** [comment]
Wojtek - do you know where in the graph to add that constraint?

ApiCommonWorkflow/Main/lib/xml/workflow/compounds.xml

**Comment by wbazant** [comment]
@jbrestel have a look now?

Someone already had the same problem with Results.CompoundMassSpec.

I didn't test this change in any way but I can!

**Comment by kathryncrouch** [comment]
Only had a quick look (it's late), but this makes sense to me.

**Pull request merged**
